### ISSUE TITLE
Mobility Issue

### ISSUE THREAD

**Issue by xDRAKONISx** [SamB440/MCRealisticPlus#2]
Hello. For some reason when I have this plugin enabled, the WASD keys do anything unless you are jumping or flying. I thought this problem was just me, but then more people logged into my server and reported the same issue. I had to uninstall the plugin because of it. It did this on my test server as well, which only has this plugin and the plugins that it is dependent upon installed.

**Comment by SamB440** [comment]
It should get fixed after a few seconds - this usually only happens after a reload or restart. Just tell your players to interact with a block and it should work, or just wait a few seconds.

**Comment by xDRAKONISx** [comment]
Unfortunately, I've tried that, and it did not fix it.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by SamB440** [comment]
This has not been reported by anyone else - show me your plugin list, and are there any errors in console? What Minecraft version are you using?

The review system is not a place to report bugs. Please read the plugin page before reporting bugs.

As quoted: The review section is not a place to report bugs. You will get NO support if you leave a review because of a bug.​

**Comment by xDRAKONISx** [comment]
I am using Minecraft 1.12. On my test server I had nothing but this plugin
and the plugins on which it depends, and there were no errors in the
console, so I know it's not conflicting with any other plugins.

On Sep 10, 2017 12:18 AM, "Sam" <notifications@github.com> wrote:

This has not been reported by anyone else - show me your plugin list, and
are there any errors in console? What Minecraft version are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SamB440/MCRealisticPlus/issues/2#issuecomment-328324843>,
or mute the thread

**Comment by SamB440** [comment]
Try latest version.

**Comment by SamB440** [comment]
Has this been solved?

**Comment by xDRAKONISx** [comment]
Well, if you wouldn't have been a jerk to me while I was simply trying to
get help with an issue, I would've been much more inclined to try the new
version. Unfortunately, however, you were a jerk, so I did not try it. Oh,
and seeing that nice little message you left with the update after I was
honest about my view of you and your plugin in my review, I'm even less
inclined to try the new version, ever use any plugin you will ever make in
the future, or recommend this or any other plugin you've ever or will ever
make to anyone I know. Moral of the story? You'll get much farther in life
if you don't treat people like shit, especially when they are coming to you
for help. Do not reply to this email.

**Comment by SamB440** [comment]
Actually, you're the one being the jerk here. I clearly left in the plugin page to not leave a review because of a bug. You'll find this on most plugins. Issue closed.

**Comment by xDRAKONISx** [comment]
Seriously? How can you say I'm being the jerk when your initial response
was basically "Well, no one else has experienced that problem, and neither
have I, so it must not exist."

**Comment by SamB440** [comment]
LOL. I didn't say 'it must not exist'.

**Comment by SamB440** [comment]
*Solved in latest update*
